Repository elementary/website, pull requests merged in 2019-10, with the labels that each got.

#2277 Mode Buttons are mutually exclusive
  docs/human-interface-guidelines.md
Labels: Bitesize

#2267 Update dependencies to clear GitHub security warnings.
  _backend/composer.lock
  _styles/countdown.css
  _styles/press.css
  package-lock.json
  package.json
Labels: Priority Critical, dependencies

#2097 Add keyboard shortcuts info to Tooltips
  docs/human-interface-guidelines.md
Labels: Size: Tiny

#2222 Clarify retrieving logs
  docs/code/os-dev.md
Labels: Size: Tiny

#2275 Fix #2258
  _styles/docs.css
Labels: Size: Tiny
